CREATE TABLE "categoria" (
	"id_categoria" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(50) NOT NULL,
	PRIMARY KEY("id_categoria")
);

CREATE TABLE "produto" (
	"id_produto" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(50) NOT NULL,
	"quantidade_estoque" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
	"unidade_medida" VARCHAR(10) NOT NULL,
	"valor_unitario" DECIMAL(10,2) NOT NULL,
	"id_categoria" INTEGER NOT NULL,
	PRIMARY KEY("id_produto"),
	CONSTRAINT "chk_estoque_positivo" CHECK ("quantidade_estoque" >= 0),
	CONSTRAINT "chk_valor_positivo" CHECK ("valor_unitario" >= 0)
);

CREATE TABLE "entrada" (
	"id_entrada" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"data_inicial" DATE NOT NULL,
	"quantidade" DECIMAL(10,2) NOT NULL,
	"id_produto" INTEGER NOT NULL,
	PRIMARY KEY("id_entrada"),
	CONSTRAINT "chk_qtd_entrada_positiva" CHECK ("quantidade" > 0)
);

CREATE TABLE "saida" (
	"id_saida" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"data_final" DATE NOT NULL,
	"quantidade" DECIMAL(10,2) NOT NULL,
	"id_produto" INTEGER NOT NULL,
	PRIMARY KEY("id_saida"),
	CONSTRAINT "chk_qtd_saida_positiva" CHECK ("quantidade" > 0)
);

ALTER TABLE "produto" ADD FOREIGN KEY("id_categoria") REFERENCES "categoria"("id_categoria");
ALTER TABLE "entrada" ADD FOREIGN KEY("id_produto") REFERENCES "produto"("id_produto");
ALTER TABLE "saida" ADD FOREIGN KEY("id_produto") REFERENCES "produto"("id_produto");

CREATE OR REPLACE VIEW "vw_estoque" AS
SELECT 
    "id_produto",
    "nome",
    "quantidade_estoque",
    "valor_unitario",
    ("quantidade_estoque" * "valor_unitario") AS "valor_total"
FROM "produto";

INSERT INTO "categoria" ("nome") VALUES 
('Detergentes e Sabões'), 
('Desinfetantes'), 
('Acessórios de Limpeza');

INSERT INTO "produto" ("nome", "quantidade_estoque", "unidade_medida", "valor_unitario", "id_categoria") VALUES 
('Sabão Líquido 5L', 15.00, 'Galão', 35.50, 1),
('Desinfetante Lavanda 1L', 42.00, 'Unidade', 8.90, 2),
('Vassoura', 8.00, 'Unidade', 14.20, 3);

INSERT INTO "entrada" ("data_inicial", "quantidade", "id_produto") VALUES 
('2026-07-10', 10.00, 1), 
('2026-07-11', 20.00, 2), 
('2026-07-12', 5.00, 3);

INSERT INTO "saida" ("data_final", "quantidade", "id_produto") VALUES 
('2026-07-14', 2.00, 1), 
('2026-07-15', 5.00, 2), 
('2026-07-16', 1.00, 3);